controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

verify_email:
    path: /verify-email/{token}
    controller: App\Controller\SecurityController::verifyUserEmail
    methods: [GET]

